[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp",
    "fastmcp",
    "httpx",
    "pydantic",
    "fastapi>=0.135.1",
    "tree-sitter",
    "tree-sitter-python",
    "google-genai",
]

[project.optional-dependencies]
dev = [
    "pytest",
]
